for line in open("mrconso_mrrel_hypernym_final_merge.csv"):
    splitline = line.split('|')
    if len(splitline) == 6 and str(splitline[5].strip('\n')) != '' and str(splitline[3].strip('\n'))!= '' and not str(splitline[3].strip('\n')) in str(splitline[5].strip('\n')):
        print(str(splitline[5].strip('\n') + " which is an example of " + str(splitline[3].strip('\n'))))
        print(str(splitline[5].strip('\n') + " which is a kind of " + str(splitline[3].strip('\n'))))
        print(str(splitline[5].strip('\n') + " a kind of " + str(splitline[3].strip('\n'))))
        print(str(splitline[5].strip('\n') + " that is a kind of " + str(splitline[3].strip('\n'))))
        print(str(splitline[5].strip('\n') + " which is a class of " + str(splitline[3].strip('\n'))))
        print(str(splitline[5].strip('\n') + " an example of " + str(splitline[3].strip('\n'))))
        print(str(splitline[5].strip('\n') + " a kind of " + str(splitline[3].strip('\n'))))
        print(str(splitline[5].strip('\n') + " a class of " + str(splitline[3].strip('\n'))))
        print(str(splitline[5].strip('\n') + " and some " + str(splitline[3].strip('\n'))))
        print(str(splitline[5].strip('\n') + " or any " + str(splitline[3].strip('\n'))))
        print(str(splitline[5].strip('\n') + " and any " + str(splitline[3].strip('\n'))))
        print(str(splitline[5].strip('\n') + " or some " + str(splitline[3].strip('\n'))))
        print(str(splitline[5].strip('\n') + " which is called" + (splitline[3].strip('\n'))))
        print(str(splitline[5].strip('\n') + " is " + str(splitline[3].strip('\n'))))
        print(str(splitline[5].strip('\n') + " is a case of " + str(splitline[3].strip('\n'))))
        print(str(splitline[5].strip('\n') + " is a " + str(splitline[3].strip('\n'))))
        print(str(splitline[5].strip('\n') + " is an " + str(splitline[3].strip('\n'))))
        print(" unlike most " + str(splitline[3].strip('\n')) + ", " + str(splitline[5].strip('\n')))
        print(" unlike all " + str(splitline[3].strip('\n')) + ", " + str(splitline[5].strip('\n')))
        print(" unlike any " + str(splitline[3].strip('\n')) + ", " + str(splitline[5].strip('\n')))
        print(" unlike other " + str(splitline[3].strip('\n')) + ", " + str(splitline[5].strip('\n')))
        print(" like most " + str(splitline[3].strip('\n')) + ", " + str(splitline[5].strip('\n')))
        print(" like all " + str(splitline[3].strip('\n')) + ", " + str(splitline[5].strip('\n')))
        print(" like any " + str(splitline[3].strip('\n')) + ", " + str(splitline[5].strip('\n')))
        print(" like other " + str(splitline[3].strip('\n')) + ", " + str(splitline[5].strip('\n')))
        print(str(splitline[3].strip('\n')) + ", including " + str(splitline[3].strip('\n')))
        print(str(splitline[3].strip('\n')) + " including " + str(splitline[3].strip('\n')))
        print(str(splitline[3].strip('\n')) + ", such as " + str(splitline[5].strip('\n')))
        print(str(splitline[3].strip('\n')) + " such as " + str(splitline[5].strip('\n')))
        print(str(splitline[5].strip('\n') + ", and other " + str(splitline[3].strip('\n'))))
        print(str(splitline[5].strip('\n') + " and other " + str(splitline[3].strip('\n'))))
        print(str(splitline[3].strip('\n')) + " include " + str(splitline[5].strip('\n')))
        print(str(splitline[3].strip('\n')) + ", especially " + str(splitline[5].strip('\n')))
        print(str(splitline[3].strip('\n')) + " especially " + str(splitline[5].strip('\n')))
        print(str(splitline[5].strip('\n') + " and any other " + str(splitline[3].strip('\n'))))
        print(str(splitline[5].strip('\n') + ", and any other " + str(splitline[3].strip('\n'))))
        print(str(splitline[5].strip('\n') + " and any " + str(splitline[3].strip('\n'))))
        print(str(splitline[5].strip('\n') + ", and any " + str(splitline[3].strip('\n'))))
        print(str(splitline[5].strip('\n') + " and other " + str(splitline[3].strip('\n'))))
        print(str(splitline[5].strip('\n') + ", and other " + str(splitline[3].strip('\n'))))
        print(str(splitline[5].strip('\n') + " and some other " + str(splitline[3].strip('\n'))))
        print(str(splitline[5].strip('\n') + ", and some other " + str(splitline[3].strip('\n'))))
        print(str(splitline[5].strip('\n') + ", and like some other " + str(splitline[3].strip('\n'))))
        print(str(splitline[5].strip('\n') + ", and like some other " + str(splitline[3].strip('\n'))))
        print(str(splitline[5].strip('\n') + ", and like other " + str(splitline[3].strip('\n'))))
        print(str(splitline[5].strip('\n') + " and like other " + str(splitline[3].strip('\n'))))
        print(str(splitline[3].strip('\n')) + ", like " + str(splitline[5].strip('\n')))
        print(str(splitline[3].strip('\n')) + " like " + str(splitline[5].strip('\n')))
        print(str(splitline[5].strip('\n') + " like other " + str(splitline[3].strip('\n'))))
        print(str(splitline[5].strip('\n') + ", like other " + str(splitline[3].strip('\n'))))
        print("such " + str(splitline[3].strip('\n')) + " as " + str(splitline[5].strip('\n')))
        print(str(splitline[5].strip('\n') + ", which is an example of " + str(splitline[3].strip('\n'))))
        print(str(splitline[5].strip('\n') + " which is an example of " + str(splitline[3].strip('\n'))))
        print(str(splitline[5].strip('\n') + ", and is an example of " + str(splitline[3].strip('\n'))))
        print(str(splitline[5].strip('\n') + " and is an example of " + str(splitline[3].strip('\n'))))
        print(str(splitline[5].strip('\n') + ", that is an example of " + str(splitline[3].strip('\n'))))
        print(str(splitline[5].strip('\n') + " that is an example of " + str(splitline[3].strip('\n'))))
        print("an example of " + str(splitline[3].strip('\n')) + " is " + str(splitline[5].strip('\n')))
        print("an example of which" + str(splitline[3].strip('\n')) + " is " + str(splitline[5].strip('\n')))
        print("an example of that" + str(splitline[3].strip('\n')) + " is " + str(splitline[5].strip('\n')))
        print(str(splitline[3].strip('\n')) + ", for example  " + str(splitline[5].strip('\n')))
        print(str(splitline[3].strip('\n')) + " for example  " + str(splitline[5].strip('\n')))
        print(str(splitline[3].strip('\n')) + " mainly " + str(splitline[5].strip('\n')))
        print(str(splitline[3].strip('\n')) + ", mainly " + str(splitline[5].strip('\n')))
        print(str(splitline[3].strip('\n')) + " mostly " + str(splitline[5].strip('\n')))
        print(str(splitline[3].strip('\n')) + ", mostly " + str(splitline[5].strip('\n')))
        print(str(splitline[3].strip('\n')) + " notably " + str(splitline[5].strip('\n')))
        print(str(splitline[3].strip('\n')) + ", notably " + str(splitline[5].strip('\n')))
        print(str(splitline[3].strip('\n')) + ", particularly " + str(splitline[5].strip('\n')))
        print(str(splitline[3].strip('\n')) + " particularly " + str(splitline[5].strip('\n')))
        print(str(splitline[3].strip('\n')) + ", principally " + str(splitline[5].strip('\n')))
        print(str(splitline[3].strip('\n')) + " principally " + str(splitline[5].strip('\n')))
        print(str(splitline[3].strip('\n')) + ", in particular " + str(splitline[5].strip('\n')))
        print(str(splitline[3].strip('\n')) + " in particular " + str(splitline[5].strip('\n')))
        print(str(splitline[3].strip('\n')) + " except " + str(splitline[5].strip('\n')))
        print(str(splitline[3].strip('\n')) + ", except " + str(splitline[5].strip('\n')))
        print(str(splitline[3].strip('\n')) + ", other than " + str(splitline[5].strip('\n')))
        print(str(splitline[3].strip('\n')) + " other than " + str(splitline[5].strip('\n')))
        print(str(splitline[3].strip('\n')) + " e.g. " + str(splitline[5].strip('\n')))
        print(str(splitline[3].strip('\n')) + ", e.g. " + str(splitline[5].strip('\n')))
        print(str(splitline[3].strip('\n')) + " i.e. " + str(splitline[5].strip('\n')))
        print(str(splitline[3].strip('\n')) + ", i.e. " + str(splitline[5].strip('\n')))
        print(str(splitline[5].strip('\n') + ", a form of " + str(splitline[3].strip('\n'))))
        print(str(splitline[5].strip('\n') + " a form of " + str(splitline[3].strip('\n'))))
        print(str(splitline[5].strip('\n') + ", a type of " + str(splitline[3].strip('\n'))))
        print(str(splitline[5].strip('\n') + " a type of " + str(splitline[3].strip('\n'))))

        #else
        #    pass